### ISSUE TITLE
Event.initEvent() has been deprecated

### ISSUE THREAD

**Issue by Sakrecoer** [lavas-project/jekyll-pwa#34]
Trying to learn how to capture the `sw.update` custom event, I found out the method used to initialize the value of the event by jekyll-pwa in `sw-register.js` has been deprecated.

https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent

I wish i could help you address it, but the paragraph above should be fairly explicit about my level with these things...

If this is known or by any other means irrelevant to you, please excuse me for the noise.

**Comment by rdy4ever** [comment]
Here's the PR: https://github.com/lavas-project/jekyll-pwa/pull/36/files

**Comment by souldanger** [comment]
latest version adressed the issue
