### ISSUE TITLE
 Migrate from Workbox v2 to v3 

### ISSUE THREAD

**Issue by DirtyF** [lavas-project/jekyll-pwa#6]
Hi, 

Do you intend to update the Workbox version used in this plugin?

Migration guide: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v2

**Comment by xiaoiver** [comment]
I'll check the migration guide later 😄

**Comment by xiaoiver** [comment]
I published `v2.0.1`, so that this plugin is using Workbox v3 now!
You can write your own Service Worker with Workbox APIs.
