### ISSUE TITLE
Adding plugins

### ISSUE THREAD

**Issue by mdelarioja** [lavas-project/jekyll-pwa#7]
Thanks for the great work on this!

It would be helpful to be able to configure the use of plugins to, for example, set expiration and limit the number of files that are cached.

**Comment by xiaoiver** [comment]
I already migrated Workbox from v2 to v3 recently.  You can upgrade this plugin to **v2.0.1**.
So that you can use **Workbox Plugins** in your `service-worker.js` like that:
```javascript
// my-service-worker.js

workbox.routing.registerRoute(
  new RegExp('/images/'),
  workbox.strategies.cacheFirst({
    cacheName: 'image-cache',
    plugins: [
      new workbox.expiration.Plugin({
        maxEntries: 20,
      }),
    ],
  })
);
```

**Comment by mdelarioja** [comment]
@xiaoiver Thank you for all your work on this!
